### ISSUE TITLE
Different number of characters

### ISSUE THREAD

**Issue by EvaLiyt** [bioDS/vcf2fasta#2]
Hello everyone, I found the output nexus file has a character number conflict between the given info in the output file and the actual sites of sequences. The clade rate for the tumour is 0.0007, and the root rate is 0.0001 for the true tree. 

The true tree with 20 cells is shown below (supposed to have .trees as the suffix):
[sequenceGeneration_psiscs.txt](https://github.com/user-attachments/files/16327107/sequenceGeneration_psiscs.txt)
Here is an example of the output file (supposed to have .nex as the suffix):
[1459.snp.vcf.txt](https://github.com/user-attachments/files/16327140/1459.snp.vcf.txt)
Here is the vcf file before conversion (supposed to have .vcf as the suffix):
[sorted_1459.snp.txt](https://github.com/user-attachments/files/16327153/sorted_1459.snp.txt)

**Comment by J-Moravec** [comment]
@EvaLiyt please, don't just close the issue without comment. If there is a problem in the vcf2fasta code and it fails at translating the vcf file into fasta/nexus, I would be glad to look into it and fix it.

**Comment by EvaLiyt** [comment]
Hi, I found there is no problem with the vcf2fasta code; it's my local machine's problem. I did not find a solution to delete this issue, so I just closed it. Thanks for asking.
